### ISSUE TITLE
Plugin only works when unpacked.

### ISSUE THREAD

**Issue by ghost** [mendelgusmao/SublimeGoCoverage#3]
On OSX I've found that this package does nothing at all after being installed from the package manager.

If you unzip the version from 'Installed Packages' into 'Packages', it starts working.

**Comment by mwf** [comment]
@alandaws it works for me.

I recommend you to check your Sublime console on startup.
Maybe it's lacking of GOPATH env var.
When it's not set the plugin crashes and can only be reloaded manually when updating Packages folder.
Like this:
```
reloading plugin Go Coverage.SublimeGoCoverage
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/ikorolev/Library/Application Support/Sublime Text 3/Installed Packages/Go Coverage.sublime-package/SublimeGoCoverage.py", line 8, in <module>
  File "./python3.3/os.py", line 656, in __getitem__
KeyError: 'GOPATH'
```
